### ISSUE TITLE
ControlBuilder import dosent work

### ISSUE THREAD

**Issue by Blendan** [mkheck/DialogFX#6]
`import javafx.scene.control.ControlBuilder;`

Error: `Can't resolve symbole 'ControlBuilder'`

**Comment by mkheck** [comment]
Hi,

This is due to the relocation of the JavaFX namespace in recent versions of Java. I don't actively maintain this library, but I would happily approve pull requests if it's still of value to you.

Best,
Mark

**Comment by Blendan** [comment]
thanks for the answer
